name       : seatd
version    : 0.6.4
release    : 2
source     :
    - https://git.sr.ht/~kennylevinsen/seatd/archive/0.6.4.tar.gz : 3d4ac288114219ba7721239cafee7bfbeb7cf8e1e7fd653602a369e4ad050bd8
homepage   : https://sr.ht/~kennylevinsen/seatd/
license    : MIT
component  : desktop.library
summary    : A minimal seat management daemon, and a universal seat management library
description: |
    A minimal seat management daemon, and a universal seat management library. Seat management takes care of mediating access to shared devices (graphics, input), without requiring the applications needing access to be root.
setup      : |
    %meson_configure -Dlibseat-logind=systemd
build      : |
    %ninja_build
install    : |
    %ninja_install
