name       : seatd
version    : 0.6.2
release    : 1
source     :
    - https://git.sr.ht/~kennylevinsen/seatd/archive/0.6.2.tar.gz : 1e2745ea39266de40d5beb24011782da95468b81ecfa410dd0db5ff75c665727
license    : MIT
component  : desktop.library
summary    : A minimal seat management daemon, and a universal seat management library.
description: |
    A minimal seat management daemon, and a universal seat management library.
setup      : |
    %meson_configure -Dlibseat-logind=systemd
build      : |
    %ninja_build
install    : |
    %ninja_install
